// Generated by 'unplugin-auto-import'
export {}
declare global {
  const CmsImageNew: typeof import('./src/components/index')['CmsImageNew']
  const CmsTextNew: typeof import('./src/components/index')['CmsTextNew']
  const viteEnvD: typeof import('./src/vite-env.d')['default']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    readonly CmsImageNew: UnwrapRef<typeof import('./src/components/index')['CmsImageNew']>
    readonly CmsTextNew: UnwrapRef<typeof import('./src/components/index')['CmsTextNew']>
    readonly viteEnvD: UnwrapRef<typeof import('./src/vite-env.d')['default']>
  }
}
